version: '3'

services: 
  web:
    image: node
    restart: always
    ports:  
      - 8080:8080
    volumes: 
      - ./workspace:/home/node
    tty: true
    command: node /home/node/app.js
  
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: chatappdb
    volumes: 
      - ./mongodb/db:/data/db
